# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.3
- 1.7.1
services:
  - postgresql
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - SNAP_POSTGRESQL_HOST=127.0.0.1
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: cRgpIcYEMkRFt6Zwn0Z1k/XSlW2BGe7LsmowgVzqihYhOiE7MopQBJw3UlJz0UH7coqhCsxJ+dwYsFGCz08aOYws9rDZC/895VZJifCToFeORdhzHzIYlO+IQnvgZmFqWryVcbnIiQJxpIOzI8FsidqPZTzVamdDWoWq74mcwclSuyCFFA9xeI0VHTnUAvGIN9cq+JuPHlyqvVkatn2KZjVoXzpr9SZ981aJPpxal25jI6ehZ1d9JOS4a7tqSmIz+fj83ZWoeIJ60IRXwjqUs1XEqqfNxuYrrAVKTDGevw+B208Yr2CKgJpcIQYroiUGk96fxw4CnsoAj9TGyWvLcFVys5wmKRQt/qNyiyu4fOSf2I5drgkAzgB3lH0ajoUdiWcmNBbENTbCfB//mhTS8g867rFfeT4NfkX3KosajtR0C+7CbiCxyIQHDnZj5Gp0zAzSM6r7hm8TciO2ZUt+4KbhAPxMvUCA8TAlJi0qx9RVLzFAn2O9GnBEH+qLWmBcfi4uOidhNGOIuhH+9y1O91+cAtB7QumzpHIfle4FrvxeUg4E/3yX1AXuUw7b80WvAuzw6RVY8zmEaNKERK+2c6hfjm76dGUmzlwlZxwC5SS06+XDUh2dTtQdUNR9un2dXGpj4QkRvf1t0necIQrESSQXfQ0M2mX4nwpsTNfe3tk=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-postgresql
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: cRgpIcYEMkRFt6Zwn0Z1k/XSlW2BGe7LsmowgVzqihYhOiE7MopQBJw3UlJz0UH7coqhCsxJ+dwYsFGCz08aOYws9rDZC/895VZJifCToFeORdhzHzIYlO+IQnvgZmFqWryVcbnIiQJxpIOzI8FsidqPZTzVamdDWoWq74mcwclSuyCFFA9xeI0VHTnUAvGIN9cq+JuPHlyqvVkatn2KZjVoXzpr9SZ981aJPpxal25jI6ehZ1d9JOS4a7tqSmIz+fj83ZWoeIJ60IRXwjqUs1XEqqfNxuYrrAVKTDGevw+B208Yr2CKgJpcIQYroiUGk96fxw4CnsoAj9TGyWvLcFVys5wmKRQt/qNyiyu4fOSf2I5drgkAzgB3lH0ajoUdiWcmNBbENTbCfB//mhTS8g867rFfeT4NfkX3KosajtR0C+7CbiCxyIQHDnZj5Gp0zAzSM6r7hm8TciO2ZUt+4KbhAPxMvUCA8TAlJi0qx9RVLzFAn2O9GnBEH+qLWmBcfi4uOidhNGOIuhH+9y1O91+cAtB7QumzpHIfle4FrvxeUg4E/3yX1AXuUw7b80WvAuzw6RVY8zmEaNKERK+2c6hfjm76dGUmzlwlZxwC5SS06+XDUh2dTtQdUNR9un2dXGpj4QkRvf1t0necIQrESSQXfQ0M2mX4nwpsTNfe3tk=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-postgresql
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: ggXy1z0CjTqnX357/qfFiP6zut0m0odp/s/fYBnuogKP4FsvUzmT9VceAuivT40u4nWBDSQZMOaV2HBalIeN3DpuqPQ2bBwVC1WeYrOp2zVecOFHXmQEf/BXTC5IemQjh+HCKUUP88knVkXS/uhD6J8R9nvA1CwHDghU1ybCw/AY5MN4FuHFE5nR5y+OH6zIYVIyQD7pLXNNVGrGqfkQPaiwMpwRznRJrgu3OX4biYA6w85aeisSu6JJjYwMOW6ySliFyd7qbQFXjUGF1Ua1LrtdH3Az1CvGLzcMdDQw4hyFovUxkFwCQvd4Tz6kAzGPxANAPiQlh4liIcfyKSvFTZEK0qa7WB3ZvS+TVE/08IVFrztwwkParn+DITSrpS07vpO8JzRT2EOw4e2LJZB8OBh1FBDaIQkL0KuGwj2mLVBUB72kmy4W2sXgAWl4ohRk+Jn0L3E9qm2PfNx9YcmS+qHlZdndhJsy/EJyI43Svbv4Cz7OWzOFbjQZyA+ZeCGn+VXGuicRSfn669n0qVaCh1802M+Vn71YEOPiGaD7F6f55t+0geGEuuxcm1EWXSvLlVSdrULio0MGnoQImEF8u3z3Enrl0+pW43Lvv0C+PAEQbp4MiBQ5zbl8tm1oZ3PBNCBQlCqzx0rgrsb4S+8u/fWtpXiFmFLZtKjEgu2fyWU=
  file:
    - release/snap-plugin-publisher-postgresql_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-publisher-postgresql
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
